# Create authorized_keys file with Telepy public key
# Run this command before starting the container:
# mkdir -p ~/.ssh && echo "${telepy_public_key}" > ~/.ssh/authorized_keys

services:
  telepy-tunnel:
    image: alpine/autossh:latest
    container_name: telepy-tunnel
    restart: unless-stopped
    ports:
      - "${reverse_port}:${reverse_port}"
    volumes:${key_mount}
    command: >
      autossh
      -M 0
      -o "ServerAliveInterval 30"
      -o "ServerAliveCountMax 3"
      -o "StrictHostKeyChecking=no"
      -o "UserKnownHostsFile=/dev/null"${key_option}
      -p ${reverse_server_ssh_port}
      -NR '*:${reverse_port}:localhost:${ssh_port}'
      telepy@${server_domain}
    environment:
      - AUTOSSH_GATETIME=0
      - AUTOSSH_PORT=0
