
commonRouterSettings: &commonRouterSettings
  entryPoints:
    - web

backendRouterSettings: &backendRouterSettings
  <<: *commonRouterSettings
  service: backend-service

frontendServiceSettings: &frontendServiceSettings
  loadBalancer:
    servers:
      - url: "http://frontend:3000"

backendServiceSettings: &backendServiceSettings
  loadBalancer:
    servers:
      - url: "http://backend:8000"

http:
  routers:
    frontend:
      <<: *commonRouterSettings
      rule: "PathPrefix(`/`)"
      service: frontend-service

    backend-api:
      <<: *backendRouterSettings
      rule: "PathPrefix(`/api`)"

    backend-tunnel-sharing:
      <<: *backendRouterSettings
      rule: "PathPrefix(`/tunnels/share`) || PathPrefix(`/tunnels/unshare`) || PathPrefix(`/tunnels/shared-users`) || PathPrefix(`/tunnels/available-users`) || PathPrefix(`/tunnels/update-permission`) || PathPrefix(`/tunnels/server`)"
      priority: 100

    backend-websocket:
      <<: *backendRouterSettings
      rule: "PathPrefix(`/ws`)"

  services:
    frontend-service:
      <<: *frontendServiceSettings

    backend-service:
      <<: *backendServiceSettings

